# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

SPLIT_KEYBOARD = yes
DEFAULT_FOLDER = sofle/rev1
# SWAP_HANDS_ENABLE = yes


OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes

WPM_ENABLE = yes

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE	= no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE = no
SLEEP_LED_ENABLE = yes
